import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserRoleUser1771574909953 implements MigrationInterface {
    name = 'AddUserRoleUser1771574909953'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" DROP CONSTRAINT "FK_purchase_order_activities_purchase_order_id"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" DROP CONSTRAINT "FK_purchase_order_activities_user_id"`);
        await queryRunner.query(`ALTER TABLE "storage_locations" DROP CONSTRAINT "FK_storage_locations_parent_id"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_from_location_id"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_to_location_id"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_stock_transfer_items_location_id"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_insurance_claims_sale"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_insurance_claims_provider"`);
        await queryRunner.query(`ALTER TABLE "physical_count_items" DROP CONSTRAINT "FK_physical_count_items_location_id"`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" DROP CONSTRAINT "FK_settings_facility"`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" DROP CONSTRAINT "FK_settings_medicine"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_recall_facility"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_recall_batch"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_recall_medicine"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_recall_initiated_by"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_recall_completed_by"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_variance_facility"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_variance_medicine"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_variance_batch"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_variance_counted_by"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_variance_approved_by"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_batches_expiry_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_organizations_subscription"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_facility_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sale_items_medicine_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stock_movements_facility_med"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_facility_medicine_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_token_hash"`);
        await queryRunner.query(`ALTER TABLE "medicines" DROP COLUMN "cost_price"`);
        await queryRunner.query(`ALTER TABLE "facilities" DROP COLUMN "tin_number"`);
        await queryRunner.query(`ALTER TABLE "facilities" DROP COLUMN "ebm_device_serial"`);
        await queryRunner.query(`ALTER TABLE "facilities" DROP COLUMN "ebm_sdcid"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "customer_tin"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "ebm_receipt_number"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "invoice_type"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "tax_category"`);
        await queryRunner.query(`ALTER TYPE "public"."drug_schedule_enum" RENAME TO "drug_schedule_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."medicines_drug_schedule_enum" AS ENUM('unclassified', 'prescription_only', 'controlled_substance_sch_ii', 'controlled_substance_sch_iii', 'controlled_substance_sch_iv', 'pharmacist_only')`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" TYPE "public"."medicines_drug_schedule_enum" USING "drug_schedule"::"text"::"public"."medicines_drug_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" SET DEFAULT 'unclassified'`);
        await queryRunner.query(`DROP TYPE "public"."drug_schedule_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'patient', 'doctor', 'admin', 'super_admin', 'facility_admin', 'owner', 'cashier', 'pharmacist', 'store_manager', 'auditor')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "alerts"."severity" IS 'info, warning, critical, out_of_stock'`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "vat_rate" SET DEFAULT '0.18'`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_role_enum" RENAME TO "invitations_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum" AS ENUM('user', 'patient', 'doctor', 'admin', 'super_admin', 'facility_admin', 'owner', 'cashier', 'pharmacist', 'store_manager', 'auditor')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" TYPE "public"."invitations_role_enum" USING "role"::"text"::"public"."invitations_role_enum"`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" SET DEFAULT 'pharmacist'`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_6a368689710b119486785bf8cc" ON "insurance_claims" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_671d4b8cc352e88797b8f11119" ON "insurance_claims" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ca706836c27e988e1e3a62811" ON "insurance_claims" ("sale_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_426c9eb7d62836d8ce4fc3bef1" ON "medicine_facility_settings" ("facility_id", "medicine_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" ADD CONSTRAINT "FK_7e5c2960f6548f92f30defb823b" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" ADD CONSTRAINT "FK_cca6eef21f85bcfb13517ff4702" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_locations" ADD CONSTRAINT "FK_d09e847387b8e2590a3b45bcb17" FOREIGN KEY ("parent_id") REFERENCES "storage_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_711c506d7f6243ea992c6013bdd" FOREIGN KEY ("from_location_id") REFERENCES "storage_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_c7d2fc2780738acf60aeda24550" FOREIGN KEY ("to_location_id") REFERENCES "storage_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_243cdc555f941db13a82aac67a6" FOREIGN KEY ("location_id") REFERENCES "storage_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_9ca706836c27e988e1e3a62811b" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_671d4b8cc352e88797b8f11119a" FOREIGN KEY ("provider_id") REFERENCES "insurance_providers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_count_items" ADD CONSTRAINT "FK_90f6784841fdaf17b87f454d919" FOREIGN KEY ("location_id") REFERENCES "storage_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" ADD CONSTRAINT "FK_6d541af3e147b3fbb4353d526f8" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" ADD CONSTRAINT "FK_e0c41df243b3355a287a6181b70" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_fa0e3c13947259736072263fe45" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_c51830cf6c0c79e30a9e79cb37b" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_544159bec830e9fc30c565b81ee" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_11b4f6ed7c1934341b51c6f6fc0" FOREIGN KEY ("initiated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_ba1f63192d4dc0a840c008ce7b1" FOREIGN KEY ("completed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_d12f4de7d07c9df1a6722443af2" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_595fc910ae73b1dd9dd2e064341" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_32729b2608ba3aff0f52bd3724b" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_920e3958140b0dac456d363570b" FOREIGN KEY ("counted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_83058766bebb2dfe591db3cca98" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_83058766bebb2dfe591db3cca98"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_920e3958140b0dac456d363570b"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_32729b2608ba3aff0f52bd3724b"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_595fc910ae73b1dd9dd2e064341"`);
        await queryRunner.query(`ALTER TABLE "stock_variances" DROP CONSTRAINT "FK_d12f4de7d07c9df1a6722443af2"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_ba1f63192d4dc0a840c008ce7b1"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_11b4f6ed7c1934341b51c6f6fc0"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_544159bec830e9fc30c565b81ee"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_c51830cf6c0c79e30a9e79cb37b"`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" DROP CONSTRAINT "FK_fa0e3c13947259736072263fe45"`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" DROP CONSTRAINT "FK_e0c41df243b3355a287a6181b70"`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" DROP CONSTRAINT "FK_6d541af3e147b3fbb4353d526f8"`);
        await queryRunner.query(`ALTER TABLE "physical_count_items" DROP CONSTRAINT "FK_90f6784841fdaf17b87f454d919"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_671d4b8cc352e88797b8f11119a"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_9ca706836c27e988e1e3a62811b"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_243cdc555f941db13a82aac67a6"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_c7d2fc2780738acf60aeda24550"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_711c506d7f6243ea992c6013bdd"`);
        await queryRunner.query(`ALTER TABLE "storage_locations" DROP CONSTRAINT "FK_d09e847387b8e2590a3b45bcb17"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" DROP CONSTRAINT "FK_cca6eef21f85bcfb13517ff4702"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" DROP CONSTRAINT "FK_7e5c2960f6548f92f30defb823b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_426c9eb7d62836d8ce4fc3bef1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ca706836c27e988e1e3a62811"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_671d4b8cc352e88797b8f11119"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a368689710b119486785bf8cc"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum_old" AS ENUM('patient', 'doctor', 'admin', 'super_admin', 'facility_admin', 'owner', 'cashier', 'pharmacist', 'store_manager', 'auditor')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" TYPE "public"."invitations_role_enum_old" USING "role"::"text"::"public"."invitations_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" SET DEFAULT 'pharmacist'`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_role_enum_old" RENAME TO "invitations_role_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "vat_rate" SET DEFAULT 0.18`);
        await queryRunner.query(`COMMENT ON COLUMN "alerts"."severity" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('patient', 'doctor', 'admin', 'super_admin', 'facility_admin', 'owner', 'cashier', 'pharmacist', 'store_manager', 'auditor')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'patient'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."drug_schedule_enum_old" AS ENUM('unclassified', 'prescription_only', 'controlled_substance_sch_ii', 'controlled_substance_sch_iii', 'controlled_substance_sch_iv', 'pharmacist_only')`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" TYPE "public"."drug_schedule_enum_old" USING "drug_schedule"::"text"::"public"."drug_schedule_enum_old"`);
        await queryRunner.query(`ALTER TABLE "medicines" ALTER COLUMN "drug_schedule" SET DEFAULT 'unclassified'`);
        await queryRunner.query(`DROP TYPE "public"."medicines_drug_schedule_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."drug_schedule_enum_old" RENAME TO "drug_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "tax_category" character varying(2) DEFAULT 'B'`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "invoice_type" character varying(20) DEFAULT 'normal'`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "ebm_receipt_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "customer_tin" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "facilities" ADD "ebm_sdcid" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "facilities" ADD "ebm_device_serial" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "facilities" ADD "tin_number" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "medicines" ADD "cost_price" numeric(10,2)`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_token_hash" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user_id" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_facility_medicine_settings" ON "medicine_facility_settings" ("facility_id", "medicine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_stock_movements_facility_med" ON "stock_movements" ("facility_id", "medicine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sale_items_medicine_id" ON "sale_items" ("medicine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sales_status" ON "sales" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_users_facility_id" ON "users" ("facility_id") `);
        await queryRunner.query(`CREATE INDEX "idx_organizations_subscription" ON "organizations" ("subscription_status") `);
        await queryRunner.query(`CREATE INDEX "idx_batches_expiry_date" ON "batches" ("expiry_date") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_variance_approved_by" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_variance_counted_by" FOREIGN KEY ("counted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_variance_batch" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_variance_medicine" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_variances" ADD CONSTRAINT "FK_variance_facility" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_recall_completed_by" FOREIGN KEY ("completed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_recall_initiated_by" FOREIGN KEY ("initiated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_recall_medicine" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_recall_batch" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_recalls" ADD CONSTRAINT "FK_recall_facility" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" ADD CONSTRAINT "FK_settings_medicine" FOREIGN KEY ("medicine_id") REFERENCES "medicines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicine_facility_settings" ADD CONSTRAINT "FK_settings_facility" FOREIGN KEY ("facility_id") REFERENCES "facilities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_count_items" ADD CONSTRAINT "FK_physical_count_items_location_id" FOREIGN KEY ("location_id") REFERENCES "storage_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_insurance_claims_provider" FOREIGN KEY ("provider_id") REFERENCES "insurance_providers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_insurance_claims_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_stock_transfer_items_location_id" FOREIGN KEY ("location_id") REFERENCES "storage_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_to_location_id" FOREIGN KEY ("to_location_id") REFERENCES "storage_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_from_location_id" FOREIGN KEY ("from_location_id") REFERENCES "storage_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_locations" ADD CONSTRAINT "FK_storage_locations_parent_id" FOREIGN KEY ("parent_id") REFERENCES "storage_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" ADD CONSTRAINT "FK_purchase_order_activities_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_activities" ADD CONSTRAINT "FK_purchase_order_activities_purchase_order_id" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
