import { SETTINGS_KEYS } from './settings.constants';

// Local enums (copied from the former `Settings.entity.ts`) so the seeds can stay
// self-contained after the settings subsystem is removed.
export enum SettingDomain {
    LOCALIZATION = 'localization',
    CURRENCY_PRICING = 'currency_pricing',
    TAX_FISCAL = 'tax_fiscal',
    INVENTORY_RULES = 'inventory_rules',
    PROCUREMENT = 'procurement',
    CONTROLLED_MEDICINES = 'controlled_medicines',
    REPORTING = 'reporting',
    NOTIFICATIONS = 'notifications',
    INTEGRATIONS = 'integrations',
    COMPLIANCE = 'compliance',
    UI_PREFERENCES = 'ui_preferences',
    SECURITY = 'security',
}

export enum SettingValueType {
    STRING = 'string',
    NUMBER = 'number',
    BOOLEAN = 'boolean',
    JSON = 'json',
}

export enum SettingScopeType {
    TENANT = 'tenant',
    BRANCH = 'branch',
    USER = 'user',
}

export enum SettingOverrideMode {
    OPEN = 'open',
    GUARDED = 'guarded',
    STRICT = 'strict',
}

export enum TaxValueMode {
    DECIMAL = 'decimal',
    PERCENT = 'percent',
}

export enum FiscalIntegrationProvider {
    RRA_EBM = 'rra_ebm',
    RRA_VSDC = 'rra_vsdc',
    NONE = 'none',
    GENERIC = 'generic',
}

export enum InventoryReorderMode {
    MIN_MAX = 'min_max',
    REORDER_POINT = 'reorder_point',
    PAR = 'par',
    JIT = 'jit',
    SMART = 'smart',
}

export interface SettingDefinitionSeed {
    key: string;
    label: string;
    description: string;
    domain: SettingDomain;
    value_type: SettingValueType;
    allowed_scopes: SettingScopeType[];
    override_mode: SettingOverrideMode;
    constraints_schema: Record<string, any> | null;
    default_value: any;
    audit_sensitive: boolean;
    requires_approval: boolean;
    version: number;
}

export const SETTINGS_DEFINITION_SEEDS: SettingDefinitionSeed[] = [
    {
        key: SETTINGS_KEYS.LOCALIZATION_LOCALE,
        label: 'Default Locale',
        description: 'Default locale for date/number formatting.',
        domain: SettingDomain.LOCALIZATION,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH, SettingScopeType.USER],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { enum: ['en-RW', 'rw-RW', 'en-US', 'fr-FR'] },
        default_value: 'en-RW',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.LOCALIZATION_TIMEZONE,
        label: 'Timezone',
        description: 'Primary timezone used for branch operations and scheduler alignment.',
        domain: SettingDomain.LOCALIZATION,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH, SettingScopeType.USER],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            enum: ['Africa/Kigali', 'Africa/Dar_es_Salaam', 'Africa/Nairobi', 'UTC'],
        },
        default_value: 'Africa/Kigali',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.LOCALIZATION_DATE_FORMAT,
        label: 'Date Format',
        description: 'UI date format.',
        domain: SettingDomain.LOCALIZATION,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD'] },
        default_value: 'DD/MM/YYYY',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.LOCALIZATION_NUMBER_FORMAT,
        label: 'Number Format',
        description: 'Numeric separators and decimal layout.',
        domain: SettingDomain.LOCALIZATION,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['1,234.56', '1 234,56', '1.234,56'] },
        default_value: '1,234.56',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.LOCALIZATION_FIRST_DAY_OF_WEEK,
        label: 'First Day Of Week',
        description: 'Calendar week start.',
        domain: SettingDomain.LOCALIZATION,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['monday', 'sunday'] },
        default_value: 'monday',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CURRENCY_BASE,
        label: 'Base Currency',
        description: 'Primary accounting currency.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { enum: ['RWF', 'TZS', 'KES', 'USD', 'EUR'] },
        default_value: 'RWF',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CURRENCY_SYMBOL,
        label: 'Currency Symbol',
        description: 'Display symbol for money values.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { maxLength: 5 },
        default_value: 'RWF',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CURRENCY_DECIMALS,
        label: 'Currency Decimals',
        description: 'Decimal precision in UI and reports.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { min: 0, max: 4 },
        default_value: 0,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CURRENCY_ROUNDING_MODE,
        label: 'Currency Rounding Mode',
        description: 'Rounding behavior for invoice values.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { enum: ['half_up', 'half_even', 'floor', 'ceil'] },
        default_value: 'half_up',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.PRICING_DEFAULT_MARKUP_PERCENT,
        label: 'Default Markup Percent',
        description: 'Default medicine markup percentage.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 0,
            max: 500,
            guardrails: { max_from_tenant: true },
        },
        default_value: 20,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.PRICING_MAX_DISCOUNT_PERCENT,
        label: 'Maximum Discount Percent',
        description: 'Upper discount limit allowed at checkout.',
        domain: SettingDomain.CURRENCY_PRICING,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 0,
            max: 100,
            guardrails: { max_from_tenant: true },
        },
        default_value: 20,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.TAX_VAT_ENABLED,
        label: 'VAT Enabled',
        description: 'Enable or disable VAT processing.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.TAX_VAT_VALUE_MODE,
        label: 'VAT Value Mode',
        description: 'VAT value representation mode.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { enum: [TaxValueMode.DECIMAL, TaxValueMode.PERCENT] },
        default_value: TaxValueMode.DECIMAL,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.TAX_DEFAULT_VAT_RATE,
        label: 'Default VAT Rate',
        description: 'Default VAT rate for sales and procurement.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 0,
            max: 1,
            guardrails: { max_from_tenant: true },
        },
        default_value: 0.18,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.TAX_REGIME_CODE,
        label: 'Tax Regime',
        description: 'Applied tax regime code.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { enum: ['RW_STANDARD_VAT', 'RW_EXEMPT', 'RW_ZERO_RATED'] },
        default_value: 'RW_STANDARD_VAT',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.FISCAL_PROVIDER,
        label: 'Fiscal Integration Provider',
        description: 'Primary fiscal provider integration.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            enum: [
                FiscalIntegrationProvider.RRA_EBM,
                FiscalIntegrationProvider.RRA_VSDC,
                FiscalIntegrationProvider.NONE,
                FiscalIntegrationProvider.GENERIC,
            ],
        },
        default_value: FiscalIntegrationProvider.RRA_EBM,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.FISCAL_EBM_ENABLED,
        label: 'EBM Enabled',
        description: 'Enable EBM submission for branch invoices.',
        domain: SettingDomain.TAX_FISCAL,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: false,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_ENDPOINT,
        label: 'VSDC Endpoint',
        description: 'Override endpoint for VSDC bridge URL.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: process.env.RRA_EBM_BASE_URL || 'http://localhost:8080',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_CREDENTIALS_REF,
        label: 'VSDC Credentials Reference',
        description: 'Secret manager reference for VSDC credentials.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: '',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_RETRY_POLICY,
        label: 'VSDC Retry Policy',
        description: 'Retry policy for VSDC submission queue.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.JSON,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: {
            maxAttempts: 5,
            baseDelayMs: 1500,
            maxDelayMs: 120000,
            claimTtlSeconds: 300,
            batchSize: 50,
        },
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_MIN_STOCK_THRESHOLD_PERCENTAGE,
        label: 'Minimum Stock Threshold %',
        description: 'Threshold percentage for low-stock alerts.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 1,
            max: 100,
            guardrails: { min_from_tenant: true },
        },
        default_value: 10,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_EXPIRY_ALERT_DAYS,
        label: 'Expiry Alert Days',
        description: 'Days before expiry to trigger alerts.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 1,
            max: 730,
            guardrails: { min_from_tenant: true },
        },
        default_value: 90,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_EXPIRY_WARNING_DAYS,
        label: 'Expiry Warning Days',
        description: 'Days before expiry to mark warning state.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 1,
            max: 365,
            guardrails: { min_from_tenant: true },
        },
        default_value: 60,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_EXPIRY_CRITICAL_DAYS,
        label: 'Expiry Critical Days',
        description: 'Days before expiry for critical risk state.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            min: 1,
            max: 180,
            guardrails: { min_from_tenant: true },
        },
        default_value: 30,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_REORDER_MODE,
        label: 'Reorder Strategy',
        description: 'Inventory reorder strategy mode.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: {
            enum: [
                InventoryReorderMode.MIN_MAX,
                InventoryReorderMode.REORDER_POINT,
                InventoryReorderMode.PAR,
                InventoryReorderMode.JIT,
                InventoryReorderMode.SMART,
            ],
        },
        default_value: InventoryReorderMode.MIN_MAX,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_FEFO_STRICT,
        label: 'Strict FEFO',
        description: 'Enforce FEFO selection when stock exists.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_WAC_ENABLED,
        label: 'Weighted Average Costing',
        description: 'Enable weighted average costing in stock updates.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_PAR_ENABLED,
        label: 'PAR Replenishment Enabled',
        description: 'Enable PAR replenishment workflows.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_JIT_ENABLED,
        label: 'JIT Replenishment Enabled',
        description: 'Enable JIT ordering logic.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INVENTORY_ABC_ENABLED,
        label: 'ABC Classification Enabled',
        description: 'Enable ABC classification engine.',
        domain: SettingDomain.INVENTORY_RULES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CONTROLLED_RULES_ENABLED,
        label: 'Controlled Medicine Rules',
        description: 'Master toggle for controlled medicine safeguards.',
        domain: SettingDomain.CONTROLLED_MEDICINES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CONTROLLED_REQUIRE_PRESCRIPTION,
        label: 'Controlled Require Prescription',
        description: 'Require prescription for controlled medicines.',
        domain: SettingDomain.CONTROLLED_MEDICINES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CONTROLLED_REQUIRE_PATIENT_ID,
        label: 'Controlled Require Patient ID',
        description: 'Require patient identification for controlled medicines.',
        domain: SettingDomain.CONTROLLED_MEDICINES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CONTROLLED_REQUIRE_DUAL_APPROVAL,
        label: 'Controlled Dual Approval',
        description: 'Require dual approval for high-risk controlled transactions.',
        domain: SettingDomain.CONTROLLED_MEDICINES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.CONTROLLED_STRICT_SCHEDULE_ENFORCEMENT,
        label: 'Strict Schedule Enforcement',
        description: 'Strict legal schedule enforcement for controlled medicines.',
        domain: SettingDomain.CONTROLLED_MEDICINES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { guardrails: { min_from_tenant: true } },
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.RX_SCHEDULE_ENFORCEMENT_ENABLED,
        label: 'Prescription-only enforcement',
        description: 'Require a prescription record on POS for medicines marked prescription-only.',
        domain: SettingDomain.COMPLIANCE,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.SUPPLIER_REQUIRE_QUALIFIED_FOR_PO,
        label: 'Require qualified supplier for PO',
        description: 'Block new purchase orders when supplier qualification is not approved.',
        domain: SettingDomain.PROCUREMENT,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.REPORTING_DEFAULT_EXPORT_FORMAT,
        label: 'Default Export Format',
        description: 'Default format for report exports.',
        domain: SettingDomain.REPORTING,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH, SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['xlsx', 'csv', 'pdf'] },
        default_value: 'xlsx',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.REPORTING_RETENTION_DAYS,
        label: 'Reporting Retention Days',
        description: 'Retention window for reporting data extracts.',
        domain: SettingDomain.REPORTING,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { min: 30, max: 3650 },
        default_value: 365,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.NOTIFICATIONS_ESCALATION_MINUTES,
        label: 'Notification Escalation Minutes',
        description: 'Minutes before unresolved critical alert escalation.',
        domain: SettingDomain.NOTIFICATIONS,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH, SettingScopeType.USER],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { min: 5, max: 1440 },
        default_value: 30,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.NOTIFICATIONS_CHANNELS,
        label: 'Notification Channels',
        description: 'Enabled notification channels by severity.',
        domain: SettingDomain.NOTIFICATIONS,
        value_type: SettingValueType.JSON,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH, SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: null,
        default_value: {
            info: ['in_app'],
            warning: ['in_app', 'email'],
            critical: ['in_app', 'email'],
        },
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_CREDENTIALS_REF,
        label: 'EBM Credentials Reference',
        description: 'Secret manager reference path for EBM credentials.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { maxLength: 255 },
        default_value: '',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_ENDPOINT,
        label: 'EBM Endpoint',
        description: 'EBM API endpoint URL.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: { pattern: '^https?://.+' },
        default_value: 'https://ebm.rra.gov.rw/api',
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.INTEGRATIONS_EBM_RETRY_POLICY,
        label: 'EBM Retry Policy',
        description: 'Retry policy for failed EBM submissions.',
        domain: SettingDomain.INTEGRATIONS,
        value_type: SettingValueType.JSON,
        allowed_scopes: [SettingScopeType.TENANT, SettingScopeType.BRANCH],
        override_mode: SettingOverrideMode.GUARDED,
        constraints_schema: null,
        default_value: {
            max_attempts: 3,
            backoff_ms: 500,
        },
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.COMPLIANCE_AUDIT_RETENTION_DAYS,
        label: 'Audit Retention Days',
        description: 'Retention days for immutable change logs.',
        domain: SettingDomain.COMPLIANCE,
        value_type: SettingValueType.NUMBER,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: { min: 365, max: 3650 },
        default_value: 1825,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.COMPLIANCE_IMMUTABLE_LOGS_ENABLED,
        label: 'Immutable Logs Enabled',
        description: 'Enforce immutable append-only settings change logs.',
        domain: SettingDomain.COMPLIANCE,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: null,
        default_value: true,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.COMPLIANCE_SOD_ENFORCED,
        label: 'Separation Of Duty Enforcement',
        description: 'Enforce separation-of-duty policies for high-risk actions.',
        domain: SettingDomain.COMPLIANCE,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.TENANT],
        override_mode: SettingOverrideMode.STRICT,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: true,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.UI_THEME,
        label: 'Theme',
        description: 'User preferred theme.',
        domain: SettingDomain.UI_PREFERENCES,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['system', 'light', 'dark'] },
        default_value: 'system',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.UI_DASHBOARD_LAYOUT,
        label: 'Dashboard Layout',
        description: 'User preferred dashboard card density.',
        domain: SettingDomain.UI_PREFERENCES,
        value_type: SettingValueType.STRING,
        allowed_scopes: [SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: { enum: ['standard', 'compact', 'comfortable'] },
        default_value: 'standard',
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
    {
        key: SETTINGS_KEYS.UI_COMPACT_TABLES,
        label: 'Compact Tables',
        description: 'Use compact row density in tables.',
        domain: SettingDomain.UI_PREFERENCES,
        value_type: SettingValueType.BOOLEAN,
        allowed_scopes: [SettingScopeType.USER],
        override_mode: SettingOverrideMode.OPEN,
        constraints_schema: null,
        default_value: false,
        audit_sensitive: false,
        requires_approval: false,
        version: 1,
    },
];
